# Generated by Django 4.0.2 on 2022-02-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='models',
            new_name='mobile_no',
        ),
    ]
